# This is a basic workflow to help you get started with Actions

name: Formatting (pre-commit)

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:


jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install clang-format-10
      run: sudo apt-get install clang-format-10
    - uses: pre-commit/action@v2.0.0
